apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-auth-web
  namespace: lab3-auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-auth-web
  template:
    metadata:
      labels:
        app: simple-auth-web
    spec:
      containers:
        - name: simple-auth-web
          image: europe-west1-docker.pkg.dev/lab4-cicd-simple-auth/lab4-docker/simple-auth-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
