apiVersion: v1
kind: Service
metadata:
  name: simple-auth-web-service
  namespace: lab3-auth-app
spec:
  type: NodePort
  selector:
    app: simple-auth-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
